apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zk6r2b2kg-python 
  janus-idp.io/tekton: zk6r2b2kg-python
  backstage.io/kubernetes-id: zk6r2b2kg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zk6r2b2kg-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml