apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zk6r2b2kg-python
  janus-idp.io/tekton: zk6r2b2kg-python
  backstage.io/kubernetes-id: zk6r2b2kg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zk6r2b2kg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
